apiVersion: v1
kind: Service
metadata:
  name: prueba-devsecops-service
  namespace: devsecops
spec:
  type: NodePort
  selector:
    app: prueba-devsecops
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
