apiVersion: apps/v1
kind: Deployment
metadata:
  name: prueba-devsecops
  labels:
    app: prueba-devsecops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prueba-devsecops
  template:
    metadata:
      labels:
        app: prueba-devsecops
    spec:
      containers:
        - name: prueba-devsecops
          image: andres0118/prueba-devsecops:44d7e59
          ports:
            - containerPort: 80
