apiVersion: v1
kind: Service
metadata:
  name: prueba-devsecops-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: prueba-devsecops
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30080