apiVersion: v1
kind: Service
metadata:
  name: prueba-devsecops-service
  namespace: default
spec:
  type: {{ .Values.service.type }}
  selector:
    app: prueba-devsecops
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}