name: Verificar Secrets

on:
  workflow_dispatch:

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar variables (ocultando valores reales)
        run: |
          echo "ARGOCD_AUTH_TOKEN: OK"
          echo "ARGOCD_SERVER: OK"
          echo "DOCKERHUB_TOKEN: OK"
          echo "DOCKERHUB_USERNAME: OK"
          echo "KUBE_CONFIG: OK"
