name: CI/CD con ArgoCD y Docker Hub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del cÃ³digo
        uses: actions/checkout@v4

      - name: Login en Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Construir y subir imagen
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/prueba-devsecops:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/prueba-devsecops:latest

      - name: Configurar Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig
          export KUBECONFIG=kubeconfig
          kubectl get nodes

      - name: Desplegar con ArgoCD
        run: |
          argocd login ${{ secrets.ARGOCD_SERVER }} --auth-token ${{ secrets.ARGOCD_AUTH_TOKEN }} --insecure
          argocd app sync prueba-devsecops --grpc-web || echo "No existe la app, saltando."
