name: CI/CD GitOps - Build & Update YAML Plano

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    env:
      IMAGE_REPO: andres0118/prueba-devsecops
      # Ruta del manifiesto de Kubernetes a modificar
      DEPLOYMENT_MANIFEST: k8s/deployment.yaml 

    steps:
      - name: Checkout C√≥digo Fuente
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT_TOKEN }} 

      
      - name: üêã Login en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: üè∑Ô∏è Definir Tag con SHA del Commit (7 caracteres)
        id: tag
        run: echo "NEW_TAG=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: üì¶ Construir y Subir Imagen a Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_REPO }}:${{ env.NEW_TAG }},${{ env.IMAGE_REPO }}:latest

      
      - name: üîß Instalar yq (YAML Processor)
        run: sudo snap install yq

      - name: üìù Actualizar la Etiqueta de la Imagen en deployment.yaml
        run: |
          echo "Actualizando imagen a ${{ env.IMAGE_REPO }}:${{ env.NEW_TAG }}"
          
          # La sintaxis de yq para modificar el primer contenedor en el Deployment YAML
          yq e '.spec.template.spec.containers[0].image = "${{ env.IMAGE_REPO }}:${{ env.NEW_TAG }}"' -i ${{ env.DEPLOYMENT_MANIFEST }}
          
          echo "Contenido de deployment.yaml actualizado (Snippet):"
          yq e '.spec.template.spec.containers[0].image' ${{ env.DEPLOYMENT_MANIFEST }}

      - name: ‚¨ÜÔ∏è Commit y Push del cambio GitOps
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'GitOps: Despliegue de imagen con tag ${{ env.NEW_TAG }}'
          file_pattern: ${{ env.DEPLOYMENT_MANIFEST }}
