name: CI-CD GitOps Pipeline - Prueba DevSecOps

on:
  push:
    branches: ["main"]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/prueba-devsecops

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:${{ github.sha }}
          docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest

      - name: Update Helm values.yaml
        run: |
          sed -i "s|tag: .*|tag: \"${{ github.sha }}\"|" helm/prueba-devsecops/values.yaml

      - name: Commit and push Helm update
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add helm/prueba-devsecops/values.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push
